# Generated by Django 5.2 on 2025-05-21 14:18

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=curriculum.models.save_subject_image, verbose_name='Subject Image'),
        ),
    ]
